name: Generate Readme

on:
  workflow_run:
    workflows: ["Enrich List"]
    types:
      - completed
  
  push:
    paths:
      - 'awesome-lock.json'
      - 'readme.template'
  
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install awelist
        run: |
          go install github.com/0xmzn/awelist/cmd/awelist@refactor
        env:
          GOPROXY: direct

      - name: Generate Readme
        run: awelist generate -o README.md readme.template

      - name: Commit README.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update README.md [skip ci]"
          file_pattern: 'README.md'